print("How old are you:?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
print("What is your street address?", end=' ')
address = input()
print(f"So, you're {age} old, {height} tall and {weight} heavy.")
print(f"And you live at {address}. Nice!")
